# Generated by Django 4.2.3 on 2023-07-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('PR', 'Processing'), ('CO', 'Complete')], default='UP', max_length=2)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
